version: '3.3'
services:
  cubemoji:
    build: .
    container_name: "cubemoji_${VERSION}"
    restart: unless-stopped
    volumes:
      - /mnt/extdr/cubemoji/data/:/usr/src/cubemoji/data
    logging:
          driver: journald
          options:
            tag: 'cubemoji_${VERSION}'