app = "cubemoji"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[build]
  image = "quay.io/cubismod/cubemoji:old-permission-gatherer275c7f10"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  internal_port = 7923
  processes = ["app"]
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = "80"
  
  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"

   [[services.http_checks]]
    interval = "20s"
    # increase grace period for troubleshooting
    grace_period = "100s"
    method = "get"
    path = "/status"
    protocol = "http"
    timeout = "10s"
    tls_skip_verify = false
    restart_limit = 2

[mounts]
source="cm_data"
destination="/usr/src/cubemoji/data/"

[[statics]]
  guest_path = '/usr/src/cubemoji/static/emoji'
  url_prefix = '/emotes'

[[statics]]
  guest_path = '/usr/src/cubemoji/static/favicon'
  url_prefix = '/favicon'


[metrics]
port=9091
path='/metrics'
