app = "cubemoji"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  image = 'registry.gitlab.com/cubismod/cubemoji:latest'

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  internal_port = 7923
  processes = ["app"]
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

   [[services.http_checks]]
    interval = 10000
    grace_period = "10s"
    method = "get"
    path = "/"
    protocol = "http"
    timeout = 2000
    tls_skip_verify = false

[mounts]
source="cm_data"
destination="/usr/src/cubemoji/data/"

[[statics]]
  guest_path = '/static/emotes'
  url_prefix = '/emotes'

[[statics]]
  guest_path = '/static/pug'
  url_prefix = '/list'