version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    versioning-strategy: "increase"
    auto-merge: true
    open-pull-requests-limit: -1
  
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    versioning-strategy: "increase"
    open-pull-requests-limit: -1
